spring:
  config:
    activate:
      on-profile: kellmer
  servlet:
    multipart:
      max-file-size: 50MB
  main:
    allow-bean-definition-overriding: true
  jackson:
    time-zone: America/Sao_Paulo
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false
        format_sql: true
        hbm2ddl:
          auto: none
        temp:
          use_jdbc_metadata_defaults: false
    open-in-view: false
  datasource:
    url: jdbc:postgresql://192.168.0.9:5432/kellmertrack
    #url: jdbc:postgresql://200.195.171.98:5440/grupohobi
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
      schema: public
      idle-timeout: 600000
      max-lifetime: 1200000
  sql:
    init:
      platform: postgres/
jwt:
  secret: secret

