package kellmertrackbackend.model.dto

data class AlvaraConstrucaoDTO(
    val indicacaoFiscal: String,
    val inscricaoImobiliaria: String?,
    val dataCriacaoAlvara: String?,
    val dataInicioObra: String?,
    val dataConclusaoObra: String?,
    val logradouro: String,
    val numero: String,
    val bairro: String,
    val grupoZoneamento: String,
    val abrangencia: String,
    val quantidadePavimentos: String,
    val quantidadeUnidadesResidenciais: String,
    val quantidadeUnidadesNaoResidenciais: String,
    val numeroAlvara: String,
    val usoAlvara: String?,
    val sobUsoAlvara: String?,
    val finalidade: String,
    val materiais: String,
    val metragemAreaRemanescente: String,
    val metragemConstruidaLote: String,
    val numeroCapacsUtilizadas: String,
    val areaAdicionalConstrucao: String,
    val areaLiberada: String,
    val metragemAreaReformaAlvara: String,
    val quantidadeBlocosAlvara: String,
    val quantidadeSubSoloAlvara: String,
    val autorProjeto: String?,
    val numeroRegistroCreaCauAu: String?,
    val responsavelTecnico: String?,
    val numeroRegistroCreaCauRt: String?,
    val firmaConstrutora: String?,
    val numeroCvco: String?,
    val tipoVistoria: String?,
    val dataVistoria: String?
) {
}